[package]
name = "onnx-spirv"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [ "crates/onnx-graph", "crates/onnx-import"]

[workspace.dependencies]
onnx-graph = { path = "crates/onnx-graph" }
onnx-rwkv = { path = "crates/onnx-import" }