[package]
name = "onnx-rwkv"
version = "0.1.0"
edition = "2024"

[dependencies]
onnx-graph = {workspace = true}
candle-core = {git = "https://github.com/huggingface/candle", default-features=false}
prost = "0.13.5"
