name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Dependencies
      run: "sudo apt install -y libprotobuf-dev protobuf-compiler mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
